version: '3.7'

services:
  backend:
    container_name: silesiasolar_backend
    build: ./
    command: python silesiasolar_backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - default_db
      - influx

  default_db:
    container_name: silesiasolar_default_db
    image: postgres:12.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  influx:
    container_name: silesiasolar_influx_db
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb/data
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
  influxdb_data:
