version: '3.3'

services:
  backend:
    container_name: silesiasolar_backend
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - default_db
      - influx
    networks:
      - default_network

  default_db:
    container_name: silesiasolar_default_db
    image: postgres:12.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    networks:
      - default_network

  influx:
    container_name: silesiasolar_influx_db
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb/data
    env_file:
      - ./.env.dev
    networks:
      - default_network

  grafana:
    container_name: silesiasolar_grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - default_network
    depends_on:
      - influx
    env_file:
      - ./.env.dev
    volumes:
      - ./grafana:/etc/grafana
      - grafana_data:/var/lib/grafana



  modbustcp_server:
    build: ../virtual_modbustcp_server
    command: python -u modbustcp_server.py
    ports:
      - 502:502
    networks:
      - default_network

volumes:
  postgres_data:
  influxdb_data:
  grafana_data:
  provisioning:

networks:
  default_network:
    driver: bridge

