# config file version
apiVersion: 1


# list of datasources to insert/update depending
# what's available in the database
datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  orgId: 1
  url: http://silesiasolar_influx_db:8086
  password: admin
  user: admin
  database: influx_default
  isDefault: true
  editable: false